### ISSUE TITLE
microRNA Analysis

### ISSUE THREAD

**Issue by pasconfilho** [calebclass/Shiny-NanoTube#6]
I hope this email finds you well. I'm reaching out because I'm encountering some difficulties using NanoTube for my microRNA analysis.
I wanted to inquire if it's possible to use NanoTube with microRNA data. If so, could you provide any guidance on how to properly configure it for this type of analysis?

**Comment by calebclass** [comment]
Hello! So sorry for the delay. Because the NanoTube does not currently handle the ligation controls in microRNA analysis, I might suggest starting with the NanoString nSolver application.  But if you're not worried about ligation normalization or if ligation normalization has already been conducted, the NanoTube should generally work ok.  For example, if your data were already normalized and saved in a csv file, you could use something like this:

```

# These are just the example files
csv_data <- system.file("extdata", 
                        "GSE117751_expression_matrix.csv", 
                        package = "NanoTube")
sample_info <- system.file("extdata", 
                           "GSE117751_sample_data.csv", 
                           package = "NanoTube")

dat2 <- processNanostringData(nsFile = csv_data,
                             sampleTab = sample_info, 
                             idCol = "GEO_Accession", 
                             groupCol = "Sample_Diagnosis",
                             normalization = "none") 
```

Good luck! Happy to help further if needed.
-Caleb
